sudo: required
dist: trusty
services:
 - docker

env:
  DOCKER_COMPOSE_VERSION: 1.7.1

before_install:
  - sudo apt-get -yqq update
  - sudo apt-get -yqq -o Dpkg::Options::="--force-confold" install docker-engine
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

install:
  - docker-compose --file=artifacts/test/docker-compose.yml build

script:
  - docker-compose --file=artifacts/test/docker-compose.yml up -d
  - docker-compose --file=artifacts/test/docker-compose.yml run --user www-data backend /bin/bash -c 'cd packages/domain/ && bin/phpspec run --format pretty'
  - docker-compose --file=artifacts/test/docker-compose.yml run --user www-data backend /bin/bash -c 'cd packages/infrastructure/ && bin/phpspec run --format pretty'
  - docker-compose --file=artifacts/test/docker-compose.yml run --user www-data backend /bin/bash -c 'cd packages/infrastructure/ && bin/phpunit --testdox'
  - docker-compose --file=artifacts/test/docker-compose.yml run --user www-data backend /bin/bash -c 'bin/behat'
