TPE\Domain\Party\Party:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            type: string
            groups: [List, Show]
        name:
            expose: true
            type: string
            groups: [List, Show]
        acronym:
            expose: true
            type: string
            groups: [List, Show]
        programme:
            expose: true
            type: string
            groups: [List, Show]
