TPE\Domain\Party\Policy:
    exclusion_policy: ALL
    properties:
        sources:
            expose: true
            type: array
            groups: [List, Show]
        content:
            expose: true
            type: string
            groups: [List, Show]
            access_type: public_method
            read_only: true
            accessor:
                getter: getContentInHtml
    virtual_properties:
        getPartyId:
            expose: true
            type: string
            groups: [List, Show]
        getPartyName:
            expose: true
            type: string
            groups: [List, Show]
        getScopeId:
            expose: true
            type: string
            groups: [List, Show]
        getScopeName:
            expose: true
            type: string
            groups: [List, Show]
