TPE\Domain\Party\Policy:
  type: entity
  table: tpe_policy
  indexes:
    policy_id_idx:
      columns: [ id ]
  id:
    id:
      type: string
      length: 255
  fields:
    sources:
      type: json_array
    content:
       type: text
  manyToOne:
    field:
      targetEntity: TPE\Domain\Field\Field
      inversedBy: policies
      joinColumns:
          field:
            referencedColumnName: id
    party:
      targetEntity: TPE\Domain\Party\Party
      inversedBy: policies
      joinColumns:
          party:
            referencedColumnName: id
