sylius_resource:
    resources:
        app.ambito:
            driver: doctrine/orm
            classes:
                model: TPE\Dominio\Ambito\Ambito
                repository: TPE\Infraestructura\Ambito\AmbitoBaseDeDatosRepositorio

fos_rest:
    disable_csrf_role: ROLE_API
    view:
        formats:
            json: true
            xml:  true
    format_listener:
        rules:
            - { path: '^/', priorities: ['json', 'xml'], fallback_format: json, prefer_extension: true }
