sylius_resource:
    resources:
        app.scope:
            driver: doctrine/orm
            classes:
                model: TPE\Domain\Scope\Scope
                repository: TPE\Infrastructure\Scope\ScopeDBRepository
        app.party:
            driver: doctrine/orm
            classes:
                model: TPE\Domain\Party\Party
                repository: TPE\Infrastructure\Party\PartyDBRepository
        app.policy:
            driver: doctrine/orm
            classes:
                model: TPE\Domain\Party\Policy
                repository: TPE\Infrastructure\Party\PolicyDBRepository
        app.myprogramme:
            driver: doctrine/orm
            classes:
                model: TPE\Domain\MyProgramme\MyProgramme
                repository: TPE\Infrastructure\MyProgramme\MyProgrammeDBRepository

fos_rest:
    disable_csrf_role: ROLE_API
    view:
        formats:
            json: true
            xml:  true
    format_listener:
        rules:
            - { path: '^/', priorities: ['json', 'xml'], fallback_format: json, prefer_extension: true }
