imports:
    - { resource: config_dev.yml }

parameters:
    cors_allow_origin: 'http://tuprogramaelectoral.test:9000'
    database_host: db.tuprogramaelectoral.test
    database_name: vspdb

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

