app_health_check:
    path:      /
    defaults:  { _controller: AppBundle:Default:healthCheck }

app_field_index:
    path: /fields
    methods: [GET]
    defaults:
        _controller: app.controller.field:indexAction
        _sylius:
            paginate: false
            serialization_groups: [List]

app_field_show:
    path: /fields/{id}
    methods: [GET]
    defaults:
        _controller: app.controller.field:showAction
        _sylius:
            paginate: false
            serialization_groups: [Show]
            repository:
                method: findFieldWithPoliciesById
                arguments: [$id]

app_policy_show:
    path: /policies/{id}
    methods: [GET]
    defaults:
        _controller: app.controller.policy:showAction
        _sylius:
            paginate: false
            serialization_groups: [List]

app_party_index:
    path: /parties
    methods: [GET]
    defaults:
        _controller: app.controller.party:indexAction
        _sylius:
            paginate: false

app_myprogramme_create:
    path: /myprogrammes
    methods: [POST]
    defaults:
        _controller: app.controller.myprogramme:createAction

app_myprogramme_show:
    path: /myprogrammes/{id}
    methods: [GET]
    defaults:
        _controller: app.controller.myprogramme:showAction
        _sylius:
            paginate: false
            repository:
                method: findNotExpiredById
                arguments: [$id]

app_myprogramme_update:
    path: /myprogrammes/{id}
    methods: [POST]
    defaults:
        _controller: app.controller.myprogramme:updateAction
        _sylius:
            paginate: false
            criteria:
                id: $id
                completed:  false

app_myprogramme_delete:
    path: /myprogrammes/{id}
    methods: [DELETE]
    defaults:
        _controller: app.controller.myprogramme:deleteAction
        _sylius:
            paginate: false
            criteria:
                id: $id
                completed:  true
                public:  false
