services:
    data_loader:
        class: TPE\Infrastructure\Data\Loader
        arguments:
         - @doctrine.orm.default_entity_manager

    myprogramme_form:
        class: TPE\Infrastructure\MyProgramme\MyProgrammeType
        tags:
         - { name: form.type, alias: app_myprogramme }

    interests_exist_validator:
        class: TPE\Infrastructure\MyProgramme\InterestsExistValidator
        arguments:
         - @app.repository.myprogramme
        tags:
         - { name: validator.constraint_validator, alias: interests_exist_validator }

    my_programme_is_completed_validator:
        class: TPE\Infrastructure\MyProgramme\MyProgrammeIsCompletedValidator
        tags:
         - { name: validator.constraint_validator, alias: my_programme_is_completed_validator }
