TPE\Domain\Scope\Scope:
  type: entity
  table: tpe_scope
  indexes:
    scope_id_idx:
      columns: [ id ]
  id:
    id:
      type: string
      length: 255
  fields:
    name:
      type: string
      length: 255
  oneToMany:
    policies:
      targetEntity: TPE\Domain\Party\Policy
      mappedBy: scope
