TPE\Domain\Field\Field:
  type: entity
  table: tpe_field
  indexes:
    field_id_idx:
      columns: [ id ]
  id:
    id:
      type: string
      length: 255
  fields:
    name:
      type: string
      length: 255
  oneToMany:
    policies:
      targetEntity: TPE\Domain\Party\Policy
      mappedBy: field
