version: '2'

services:
  codebase:
    image: ubuntu:15.10
    volumes:
      - ../../:/var/www

  db:
    image: postgres:9.4
    container_name: db.tuprogramaelectoral
    ports:
     - 5432:5432
    environment:
     POSTGRES_USER: root
     POSTGRES_PASSWORD: admin
     POSTGRES_DB: vspdb

  backend:
    build: backend
    container_name: api.tuprogramaelectoral
    ports:
     - 80:80
     - 9001:9000
    volumes_from:
     - codebase
    environment:
     DATABASE_HOST: db.tuprogramaelectoral
     DATABASE_NAME: vspdb
     DATABASE_USER: root
     DATABASE_PASSWORD: admin
     SYMFONY_SECRET: ThisTokenIsNotSoSecretChangeIt

  frontend:
    build: frontend
    container_name: tuprogramaelectoral
    volumes_from:
     - codebase
    ports:
     - 8080:9000
     - 35729:35729

  webtesting:
    image: selenium/standalone-firefox-debug
    container_name: webtesting.tuprogramaelectoral
    ports:
     - 4444:4444
     - 5900:5900
