db:
  image: postgres:9.4
  container_name: db.tuprogramaelectoral
  ports:
   - 5432:5432
  environment:
   POSTGRES_USER: root
   POSTGRES_PASSWORD: admin
   POSTGRES_DB: vspdb

backend:
  image: aleherse/tuprogramaelectoral:backend-dev
  container_name: api.tuprogramaelectoral
  ports:
   - 80:80
   - 9900:9900
  volumes_from:
   - codebase
  environment:
   DATABASE_HOST: db.tuprogramaelectoral
   DATABASE_NAME: vspdb
   DATABASE_USER: root
   DATABASE_PASSWORD: admin
   SYMFONY_SECRET: ThisTokenIsNotSoSecretChangeIt
  extra_hosts:
   - "hostmachine:192.168.99.1"

frontend:
  image: aleherse/tuprogramaelectoral:frontend-dev
  container_name: tuprogramaelectoral
  volumes_from:
   - codebase
  ports:
   - 9000:9000
   - 35729:35729

webtesting:
  image: selenium/standalone-firefox-debug
  ports:
   - 4444:4444
   - 5900:5900

#phantomjs:
#  image: cmfatih/phantomjs
#  ports:
#   - 4444
#  entrypoint: phantomjs
#  command: "--webdriver=4444"

#ci:
#  image: jenkins
#  ports:
#   - 8080:8080
#  volumes_from:
#   - codebase
